### ISSUE TITLE
OpenSpending/OffenerHaushalt Redesign, alte Daten wurden gelöscht

### ISSUE THREAD

**Issue by chk1** [codeformuenster/haushalt-muenster#4]
[OpenSpending](https://openspending.org/) und [OffenerHaushalt](https://offenerhaushalt.de/) haben vor einiger Zeit einen Relaunch gemacht, die alten Münsteraner Daten von 2009-2012 sind dabei wohl entfernt worden, sind aber noch auf OpenSpending zu finden ([link](https://openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:__os_imported__de-muenster-gesamt?lang=en))

Betroffener Code z.B. hier:
https://github.com/codeformuenster/haushalt-muenster/blob/gh-pages/index.html#L16
`Cannot GET /de-muenster-gesamt/embed`

Eine Verlinkte Seite aus Issue #2 führt auch zum 404: https://offenerhaushalt.de/haushalt/muenster

Und Haushaltsdaten weiterhin nur als PDF auf den Seiten der Stadt Münster...

**Comment by chk1** [comment]
Todo: 
- [x] neue Daten
- [ ] "gesamt" CSV auf OpenSpending hochladen
- [ ] OpenSpending ID bei OffenerHaushalt eintragen
- [ ] gh-pages Branch updaten

**Comment by chk1** [comment]
Datensatz bei OpenSpending:

https://openspending.org/viewer/7f037f45d2f473af5e754509a5bc9667:muenster-haushalt

Hochgeladen mit folgenden Einstellungen:

![openspendingscreen shot 2019-01-04 at 19 32 29-fullpage](https://user-images.githubusercontent.com/828496/50705133-1bbd4280-105a-11e9-89db-b62cd77be664.png)

**Comment by chk1** [comment]
Datensatz Konfiguration bei OffenerHaushalt (Tab "Werte" auf Standardeinstellungen belassen)

![image](https://user-images.githubusercontent.com/828496/50705522-6095a900-105b-11e9-96a5-b0a29de67a11.png)
![image](https://user-images.githubusercontent.com/828496/50705536-6c816b00-105b-11e9-8f54-1203ce67065a.png)

Vorschau:

![image](https://user-images.githubusercontent.com/828496/50705569-8ae76680-105b-11e9-8962-3abf8033841c.png)

**Comment by chk1** [comment]
Hochladen bei OffenerHaushalt scheint grad nicht zu funktionieren (https://github.com/okfde/offenerhaushalt.de/issues/200).

Daher poste ich hier erstmal die Config, die das Formular produziert:

```
{
  "datapackage": "7f037f45d2f473af5e754509a5bc9667:muenster-haushalt",
  "hierarchies": [
    {
      "datapackageHierarchy": "administrative_classification",
      "url": "produkt",
      "label": "Produkt"
    }
  ],
  "value": [
    {
      "field": "betrag.sum",
      "formatOptions": {
        "symbol": "",
        "decimal": ",",
        "thousand": ".",
        "precision": "0",
        "format": "%s%v",
        "postfix": "€",
        "grouping": 3
      },
      "label": "Betrag"
    }
  ],
  "scale": [
    {
      "label": "Total",
      "number": 1,
      "description": ""
    },
    {
      "label": "Pro Einwohner (313.559 in 2017)",
      "number": "313559",
      "description": "p.E."
    }
  ],
  "filters": {
    "Jahr": {
      "name": "jahr.jahr",
      "label_ref": "jahr.jahr",
      "ref": "jahr",
      "default": true,
      "defaultValue": 2016,
      "defaultLabel": "All",
      "label": "Jahr",
      "values": [
        {
          "value": "",
          "label": "All"
        },
        {
          "value": 2007,
          "label": 2007
        },
        {
          "value": 2008,
          "label": 2008
        },
        {
          "value": 2009,
          "label": 2009
        },
        {
          "value": 2010,
          "label": 2010
        },
        {
          "value": 2011,
          "label": 2011
        },
        {
          "value": 2012,
          "label": 2012
        },
        {
          "value": 2013,
          "label": 2013
        },
        {
          "value": 2014,
          "label": 2014
        },
        {
          "value": 2015,
          "label": 2015
        },
        {
          "value": 2016,
          "label": 2016
        }
      ]
    },
    "Richtung": {
      "name": "richtung.richtung",
      "label_ref": "richtung.richtung",
      "ref": "richtung",
      "default": true,
      "defaultValue": "Aufwendungen",
      "defaultLabel": "All",
      "label": "Richtung",
      "values": [
        {
          "value": "",
          "label": "All"
        },
        {
          "value": "Aufwendungen",
          "label": "Aufwendungen"
        },
        {
          "value": "Erträge",
          "label": "Erträge"
        }
      ]
    }
  },
  "level": "kommune",
  "state": "NW",
  "name": "Münster",
  "text": "Haushalt der Stadt Münster von 2007 - 2016\n\nDatenquelle ist die Stadt Münster: https://www.stadt-muenster.de/finanzen/muensters-haushalt/der-haushaltsplan.html\n\nMehr Informationen zur Datenaufbereitung befinden sich im Github Repository von Code for Münster: https://github.com/codeformuenster/haushalt-muenster"
}
```

**Comment by ubergesundheit** [comment]
Hast du nochmal was gehört?

**Comment by chk1** [comment]
Nein hab keine Rückmeldung erhalten, ich probiers die Tage nochmal, der Endpoint liefert schonmal keinen 404 mehr wie ursprünglich geschehen

**Comment by chk1** [comment]
Formular funktioniert, hier der dadurch entstandene PR: https://github.com/okfde/offenerhaushalt.de/pull/216

**Comment by chk1** [comment]
@ubergesundheit kannst du die Jahreszahl in Beschreibung des Repos ändern (2009-2016 haben wir jetzt verfügbar) oder evtl rausnehmen?

**Comment by chk1** [comment]
PR seit Mai weiterhin offen, seit Februar passiert da nichts mehr in dem Repo.

**Comment by chk1** [comment]
Der PR wurde gemerget und die Daten sind online!

https://github.com/okfde/offenerhaushalt.de/blob/gh-pages/_haushalte-data/munster.md

https://offenerhaushalt.de/haushalt/munster/

**Comment by ubergesundheit** [comment]
Danke dir!

**Comment by tomsrocket** [comment]
@chk1 Vielen Dank für Deine Ausdauer :) und super dass das geklappt hat! Ich würde die von Dir befreiten Haushaltsdaten auch auf dem Open-Data-Portal Münster verlinken, und würde Deinen Namen dazuschreiben, wäre das ok für Dich?

**Comment by chk1** [comment]
@tomsrocket Ja sehr gerne
